
** Compile

Generate =compile_commads.json= with bear
#+begin_src sh
nix shell nixpkgs#bear

make clean
bear -- make
#+end_src

** Serial Peripheral Interface (SPI)
SPI is a bus protocol so you can connect multiple devices to the same bus and control which of them is used at any time by means of their individual SS pins. MISO, MOSI, and CLK are common between all devices

| Master/Slave (OLD)         | Controller/Peripheral (NEW)          |
|----------------------------+--------------------------------------|
| Master In Slave Out (MISO) | Controller In, Peripheral Out (CIPO) |
| Master Out Slave In (MOSI) | Controller Out Peripheral In (COPI)  |
| Slave Select pin (SS)      | Chip Select Pin (CS)                 |

- CIPO (Controller In Peripheral Out) :: The Peripheral line for sending data to the Controller
- COPI (Controller Out Peripheral In) :: The Controller line for sending data to the peripherals
- SCK (Serial Clock) :: The clock pulses which synchronize data transmission generated by the Controller and one line specific for every device
- CS (Chip Select) :: the pin on each device that the Controller can use to enable and disable specific devices. When a device's Chip Select pin is low, it communicates with the Controller. When it's high, it ignores the Controller. This allows you to have multiple SPI devices sharing the same CIPO, COPI, and SCK lines.

** [[https://github.com/RobTillaart/MAX6675][MAX6675]]
The MAX6675 is a chip to convert the reading of a K-type thermocouple to a temperature. The MAX6675 only supports positive degrees Celsius.
The values are read with an precision of 0.25°C. Typical noise seen during usage are ± 0.5°C, so using a low pass filter on the temperature might be a good idea.

The working of thermocouples (TC) is based upon Seebeck effect. Different TC's have a different Seebeck Coefficient (SC) expressed in µV/°C. See http://www.analog.com/library/analogDialogue/archives/44-10/thermocouple.html

** I2C LCD

** Pins

This is for HW SPI pins. With SoftWare SPI other pins can be used.

| Name   | Uno | Notes         |
|--------+-----+---------------|
| CLOCK  |  13 | HW SPI        |
| MISO   |  12 | HW SPI        |
| MOSI   |  11 | HW SPI        |
| SELECT |  10 | Can be others |
|--------+-----+---------------|
| SDA    |  A4 |               |
| SCL    |  A5 |               |
** PID
See [[http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/][Improving the beginners PID]] for improvements to the standard PID equation


\begin{align}
\text{Output} &= K_P e(t) + K_I \int e(t) dt + K_D \frac{d}{dt} e(t) \\
\text{Where}  &: e= \text{Setpoint} - \text{Input}
\end{align}
